language: objective-c
before_script:
  - brew update
  - brew install ant
# flash player debugger
  - brew install caskroom/cask/brew-cask
  - brew cask install flash-player-debugger
# apache flex sdk
  - wget -O flex_sdk.zip http://mirrors.gigenet.com/apache/flex/4.13.0/binaries/apache-flex-sdk-4.13.0-bin.zip
  - unzip -q flex_sdk.zip -d flex_sdk
  - wget -O playerglobal.swc http://download.macromedia.com/get/flashplayer/updaters/14/playerglobal14_0.swc
  - mkdir -p flex_sdk/frameworks/libs/player/11.1
  - cp playerglobal.swc flex_sdk/frameworks/libs/player/11.1
  - echo env.PLAYERGLOBAL_HOME=libs/player > flex_sdk/env.properties
# apache flex unit
  - wget -O flexunit.zip http://mirrors.gigenet.com/apache/flex/flexunit/4.2.0/binaries/apache-flex-flexunit-4.2.0-4.12.0-bin.zip
  - unzip -q flexunit.zip
  - mkdir -p test/libs
  - cp flexunit/flexunit-*-as3_*.swc test/libs
  - cp flexunit/flexunit-cilistener-*.swc test/libs
# screenshot
  - wget -O screenshot.swc https://github.com/honzabrecka/Screenshot/releases/download/2.1.2/Screenshot_v2.1.2.swc
  - cp screenshot.swc test/libs
script:
  - ant -DFLEX_HOME "flex_sdk" -DFLEXUNIT "flexunit" -DFLASHPLAYER "$HOME/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"